extern const GeoLayout mini_pinball_geo[];
extern Lights1 mini_pinball_SlotFace_lights;
extern Lights1 mini_pinball_Slot_lights;
extern u8 mini_pinball_SlotsBorder_ci8[];
extern u8 mini_pinball_SlotsBorder_pal_rgba16[];
extern u8 mini_pinball_Slots_rgba16[];
extern Vtx mini_pinball_Cube_mesh_layer_4_vtx_0[24];
extern Gfx mini_pinball_Cube_mesh_layer_4_tri_0[];
extern Vtx mini_pinball_Cube_mesh_layer_1_vtx_0[12];
extern Gfx mini_pinball_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_mini_pinball_SlotFace[];
extern Gfx mat_revert_mini_pinball_SlotFace[];
extern Gfx mat_mini_pinball_Slot[];
extern Gfx mini_pinball_Cube_mesh_layer_4[];
extern Gfx mini_pinball_Cube_mesh_layer_1[];
