#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "group0.h"

#include "bubble/geo.inc.c"
#include "walk_smoke/geo.inc.c"
#include "burn_smoke/geo.inc.c"
#include "small_water_splash/geo.inc.c"
#include "water_wave/geo.inc.c"
#include "sparkle/geo.inc.c"
#include "water_splash/geo.inc.c"
#include "sparkle_animation/geo.inc.c"
#include "mario/geo.inc.c"

#include "ballin/geo.inc.c"
#include "mini_big_bounce/geo.inc.c"
#include "mini_marioikart/geo.inc.c"
#include "mini_snow/geo.inc.c"
#include "gold_ring/geo.inc.c"
#include "red_ring/geo.inc.c"
#include "fire_bar/geo.inc.c"
#include "retro_mini/geo.inc.c"
#include "mini_mario_kart/geo.inc.c"
#include "mini_lava/geo.inc.c"
#include "custom_heart/geo.inc.c"
#include "tutorial_base/geo.inc.c"
#include "tutorial_exclamation/geo.inc.c"
#include "mini_tutorial/geo.inc.c"
#include "mini_ethan/geo.inc.c"
#include "mini_logo/geo.inc.c"
#include "level_menu/geo.inc.c"
#include "bumper/geo.inc.c"
#include "mini_pinball/geo.inc.c"