extern const GeoLayout wmotr_area_1_geo[];
extern const GeoLayout wmotr_area_1[];
extern const Collision wmotr_area_1_collision[];
extern const MacroObject wmotr_area_1_macro_objs[];
extern Lights1 wmotr_dl_f3dlite_material_lights;
extern Lights1 wmotr_dl_sm64_material_001_lights;
extern Lights1 wmotr_dl_Fence_lights;
extern u8 wmotr_dl_SUPER_MARIO_64_4F265622_0_2_all_ci8[];
extern u8 wmotr_dl_SUPER_MARIO_64_4F265622_0_2_all_pal_rgba16[];
extern Vtx wmotr_dl_Cube_mesh_layer_1_vtx_0[90];
extern Gfx wmotr_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx wmotr_dl_Cube_mesh_layer_1_vtx_1[321];
extern Gfx wmotr_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx wmotr_dl_Cube_mesh_layer_5_vtx_0[54];
extern Gfx wmotr_dl_Cube_mesh_layer_5_tri_0[];
extern Gfx mat_wmotr_dl_f3dlite_material[];
extern Gfx mat_wmotr_dl_sm64_material_001[];
extern Gfx mat_wmotr_dl_Fence[];
extern Gfx mat_revert_wmotr_dl_Fence[];
extern Gfx wmotr_dl_Cube_mesh_layer_1[];
extern Gfx wmotr_dl_Cube_mesh_layer_5[];
