extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_f3dlite_material_lights;
extern Lights1 bob_dl_Boost_lights;
extern Lights1 bob_dl_Oil_lights;
extern Lights1 bob_dl_Rough_lights;
extern Lights1 bob_dl_Kill_lights;
extern u8 bob_dl_SUPER_MARIO_64_1EFFD4E0_0_2_all_ci8[];
extern u8 bob_dl_SUPER_MARIO_64_1EFFD4E0_0_2_all_pal_rgba16[];
extern u8 bob_dl_boostpad_ci4[];
extern u8 bob_dl_boostpad_pal_rgba16[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[549];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_1[4];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_2[4];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_3[4];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_4[4];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_4[];
extern Gfx mat_bob_dl_f3dlite_material[];
extern Gfx mat_revert_bob_dl_f3dlite_material[];
extern Gfx mat_bob_dl_Boost[];
extern Gfx mat_revert_bob_dl_Boost[];
extern Gfx mat_bob_dl_Oil[];
extern Gfx mat_bob_dl_Rough[];
extern Gfx mat_bob_dl_Kill[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
