extern const GeoLayout bumper_geo[];
extern Lights1 bumper_Red_lights;
extern Lights1 bumper_Blue_lights;
extern Lights1 bumper_Rebounding_Orb_lights;
extern u8 bumper_Rebounding_Orb_ci4[];
extern u8 bumper_Rebounding_Orb_pal_rgba16[];
extern Vtx bumper_Cylinder_mesh_layer_1_vtx_0[219];
extern Gfx bumper_Cylinder_mesh_layer_1_tri_0[];
extern Vtx bumper_Cylinder_mesh_layer_1_vtx_1[42];
extern Gfx bumper_Cylinder_mesh_layer_1_tri_1[];
extern Vtx bumper_Cylinder_mesh_layer_1_vtx_2[16];
extern Gfx bumper_Cylinder_mesh_layer_1_tri_2[];
extern Gfx mat_bumper_Red[];
extern Gfx mat_bumper_Blue[];
extern Gfx mat_bumper_Rebounding_Orb[];
extern Gfx mat_revert_bumper_Rebounding_Orb[];
extern Gfx bumper_Cylinder_mesh_layer_1[];
